version: '3'

services:
  vuttr-nodejs:
    container_name: vuttr-nodejs
    build: .
    entrypoint: ['./init.sh']
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - vuttr-mongo
    networks:
      - app-connect
    ports:
      - '3000:3000'

  vuttr-mongo:
    container_name: vuttr-mongo
    image: mongo
    volumes:
      - vuttr-mongo-data:/data
    networks:
      - app-connect
    ports:
      - '27017:27017'

volumes:
  vuttr-mongo-data:

networks:
  app-connect:
      driver: bridge
